### ISSUE TITLE
Missing documentation on important steps

### ISSUE THREAD

**Issue by cjhenck** [ASL-19/outline-distribution#4]
I was able to get this up and running with outline-bots, but there were for me a few steps that were not obvious and required substantial troubleshooting. I think it would help to add these to the documentation:

1. You need to set up URL paths for the distribution & preference apps. They are not automatic. E.g.:
```
    path('api/v1/', include('distribution.urls')),
    path('api/v1/', include('server.urls')),
```
2. Those projects use django-rest-framework, which requires authentication. Users will need to set up that authentication to their specification or, if using the [outline-bots](https://github.com/ASL-19/outline-bots) repo, add TokenAuth both as an app and as a django-rest-framework authenticator in their settings.py
3. To use the API, you need to set up a server through the admin console. Which fields are required? Do I need ipv4 & ipv6 addresses? How do I get the management URL (from the manager) or certificate details (by SSH'ing into the server and finding the has of it)? Obviously getting access to the server may be out of scope, but it would be helpful to point to where both details are stored. (`~/shadowbox/access.txt`).

It might also help to suggest users look for a "getting started with django" tutorial, though that may be obvious to anyone interested in setting this up.

Thanks for making this available!

**Comment by vfilatov87** [comment]
Hello!
Can you help me solve the problem?

`Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    main()
  File "./manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/outlinemanager/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/outlinemanager/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/home/outlinemanager/env/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/outlinemanager/env/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/outlinemanager/env/lib/python3.8/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'distribution'
`
